name = "ghu-events-moments"
main = "src/worker.js"
compatibility_date = "2024-08-13"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["*/30 * * * *"] # run every 10 minute

[vars]
GITHUB_USERNAME = "guqing"
HALO_URL = "https://guqing.io"
HALO_USERNAME = "guqing"
